### ISSUE TITLE
Unexpected error when trying to connect SIKU RV 25 W Pro WiFi V2

### ISSUE THREAD

**Issue by victori3d** [hmn/hacs-siku-integration#14]
Hi, 
i found your add on to Home Assistant and was excited to try it.
I copied the files into the custom_components/siku/ folder. Though when I try to add a vent via the UI. 
It is loading and then says. "Unexpected error".
How am i able to log the issue to narrow it down?
My vent is a Oxxify.Smart 50, which uses the same API as SIKU RV 25 W Pro WiFi V2/SIKU RV 30 DW Pro Duo WiFi V2/SIKU RV 50 W Pro WiFi V2.

I can provide you the API documentation, maybe you can check it, if it is the same for your vent.

Thanks in advance 
Patrick

**Comment by hmn** [comment]
Hi

The fans I have are V1's and I dont't think they use the same protocol as V2's because I can't use the new APP the company deployed

Unfortunately I don't have access to a V2 fan so I can't verify that this is the case

If you have some API dok I can try to see if it is a small change or if they changed everything completely

**Comment by victori3d** [comment]
[BDA_Anschluss_SmartHome_RV_V2.pdf](https://github.com/hmn/hacs-siku-integration/files/10010517/BDA_Anschluss_SmartHome_RV_V2.pdf)

Attached you find the documentation. I on my part do not have the V1 documentation.

**Comment by hmn** [comment]
the protocol is clearly different as the v2 requires a fan ID and and pin code

I might try to create a test python script to see if I can create something that is compatible with v2

**Comment by hmn** [comment]
@victori3d 

I think I have something that should be able to comunicate with a v2 fan, but before I rewrite everything to add support, could I get you to run a python test script and send me the output?

**Comment by victori3d** [comment]
Absolutely, I am more than welcome to help.

**Comment by hmn** [comment]
Try downloading https://gist.github.com/hmn/b095b88e0158d0dda5a65c7b06a2213b

and change the values in `api = SikuApiV2("192.168.8.248", 4000, "002D6E1B34565815", "1234")` to the value of your fan

it should send a read status call to the fan and log the return value

**Comment by victori3d** [comment]
I hope this helps you, unfortunately, it runs in a TimeoutError:
`2022-11-20 10:21:21,971 [DEBUG] Using proactor: IocpProactor
2022-11-20 10:21:21,971 [DEBUG] packet string: FDFD0210303032313030314335323433353731390431313131010001
2022-11-20 10:21:21,971 [DEBUG] packet string: FDFD02103030323130303143353234333537313904313131310100011100
2022-11-20 10:21:21,971 [DEBUG] sending "b'\xfd\xfd\x02\x100021001C52435719\x041111\x01\x00\x01\x11\x00'" to ('192.168.178.41', 4000)
Traceback (most recent call last):
  File "D:\Dokumente\Patrick\RPi\SIKU_Script.py", line 89, in _send_command
    data, server = s.recvfrom(256)
                   ^^^^^^^^^^^^^^^
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Dokumente\Patrick\RPi\SIKU_Script.py", line 120, in <module>
    asyncio.run(main())
  File "C:\Users\Patrick\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Patrick\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Patrick\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Dokumente\Patrick\RPi\SIKU_Script.py", line 118, in main
    await api.status()
  File "D:\Dokumente\Patrick\RPi\SIKU_Script.py", line 37, in status
    hexlist = await self._send_command(FUNC_READ, COMMAND_STATUS)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Dokumente\Patrick\RPi\SIKU_Script.py", line 97, in _send_command
    raise Exception(
Exception: Error sending command to fan controller: timed out`

**Comment by hmn** [comment]
it must be because the package I am crafting is wrong, so no response is recieved

it's a bit hard to debug without access to a fan or a packet capture of what the fan is doing when using the app

**Comment by victori3d** [comment]
Is there anyway, we can have a Teams/Discord-Session, where I can share my screen and you can debug. 
If it is too much of a hussle for you, I completely understand.
BR.

**Comment by victori3d** [comment]
Would it help, if I run wireshark to capture the package send by the app?

**Comment by hmn** [comment]
Yes a wireshark dump would definetly help both from the app and from my test

Then I should be able to see what the changes are and where I have messed up

And if that does not help a remote debug session would definetly be a good option

**Comment by victori3d** [comment]
Here is the Wireshark snapshot. It seems the app pings with length 31 while the script only pings with length 30.

iPhone APP:
Frame 42972: 73 bytes on wire (584 bits), 73 bytes captured (584 bits) on interface \Device\NPF_{2E34FFDF-5B13-47C4-975D-46D2B153EDE0}, id 0
Ethernet II, Src: ae:1d:80:a3:9b:fc (ae:1d:80:a3:9b:fc), Dst: Broadcast (ff:ff:ff:ff:ff:ff)
Internet Protocol Version 4, Src: 192.168.178.33, Dst: 255.255.255.255
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
        0000 00.. = Differentiated Services Codepoint: Default (0)
        .... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
    Total Length: 59
    Identification: 0x8cfb (36091)
    000. .... = Flags: 0x0
        0... .... = Reserved bit: Not set
        .0.. .... = Don't fragment: Not set
        ..0. .... = More fragments: Not set
    ...0 0000 0000 0000 = Fragment Offset: 0
    Time to Live: 64
    Protocol: UDP (17)
    Header Checksum: 0x7aed [validation disabled]
    [Header checksum status: Unverified]
    Source Address: 192.168.178.33
    Destination Address: 255.255.255.255
User Datagram Protocol, Src Port: 50114, Dst Port: 4000
    Source Port: 50114
    Destination Port: 4000
    Length: 39
    Checksum: 0x5bd1 [unverified]
    [Checksum Status: Unverified]
    [Stream index: 334]
    [Timestamps]
        [Time since first frame: 0.000000000 seconds]
        [Time since previous frame: 0.000000000 seconds]
    UDP payload (31 bytes)
Data (31 bytes)
    Data: fdfd021030303339303031353532343335373136043131313101b992a3fc05
    [Length: 31]

Readable Result would be: ····0039001552435716·1111······



Script:
Frame 53381: 72 bytes on wire (576 bits), 72 bytes captured (576 bits) on interface \Device\NPF_{2E34FFDF-5B13-47C4-975D-46D2B153EDE0}, id 0
Ethernet II, Src: IntelCor_48:fc:f6 (d0:57:7b:48:fc:f6), Dst: Espressi_d2:93:8e (a8:48:fa:d2:93:8e)
Internet Protocol Version 4, Src: 192.168.178.43, Dst: 192.168.178.27
User Datagram Protocol, Src Port: 51059, Dst Port: 4000
    Source Port: 51059
    Destination Port: 4000
    Length: 38
    Checksum: 0x3ee2 [unverified]
    [Checksum Status: Unverified]
    [Stream index: 465]
    [Timestamps]
        [Time since first frame: 0.000000000 seconds]
        [Time since previous frame: 0.000000000 seconds]
    UDP payload (30 bytes)
Data (30 bytes)
    Data: fdfd02103030333930303135353234333537313604313131310100010900
    [Length: 30]
Readable Result would be: ····0039001552435716·1111· ·  


Vent is constantly UDP pinging with:
Internet Protocol Version 4, Src: 192.168.178.27, Dst: 0.0.0.0
User Datagram Protocol, Src Port: 4000, Dst Port: 4001
Data (61 bytes)
Data: fdfd02103030333930303135353234333537313604313131310201010201720007008300…
[Length: 61]
Readable Result would be: ····0039001552435716·1111·····r · · · · D ··········· ·· ····

**Comment by hmn** [comment]
The command the app sends is a bit strange (or undocumented) but if I undestand the api correctly I made an error in the function and the calculation of the checksum so I updated the test script

https://gist.github.com/hmn/b095b88e0158d0dda5a65c7b06a2213b

could you try running it again

it should send the same command as the app, and as far as I can see it tries to read the device type, and the ip

**Comment by victori3d** [comment]
2022-11-20 19:44:48,856 [DEBUG] Using proactor: IocpProactor
2022-11-20 19:44:48,865 [DEBUG] packet string: FDFD021030303339303031353532343335373136043131313101B992A3
2022-11-20 19:44:48,866 [DEBUG] packet string: FDFD021030303339303031353532343335373136043131313101B992A3FC05
2022-11-20 19:44:48,867 [DEBUG] sending "fdfd021030303339303031353532343335373136043131313101b992a3fc05" size(31) to ('192.168.178.27', 4000)
2022-11-20 19:44:48,948 [DEBUG] received "b'\xfd\xfd\x02\x100039001552435716\x041111\x06\xfe\x02\xb9\x0e\x00\xfd\x92\xfe\x04\xa3\xc0\xa8\xb2\x1bC\x0b'" from ('192.168.178.27', 4000)
2022-11-20 19:44:48,956 [DEBUG] returning hexlist ['fd', 'fd', '02', '10', '30', '30', '33', '39', '30', '30', '31', '35', '35', '32', '34', '33', '35', '37', '31', '36', '04', '31', '31', '31', '31', '06', 'fe', '02', 'b9', '0e', '00', 'fd', '92', 'fe', '04', 'a3', 'c0', 'a8', 'b2', '1b', '43', '0b']
Traceback (most recent call last):
  File "D:\Dokumente\Patrick\RPi\Luefter\SIKU_Script_V2.py", line 128, in <module>
    asyncio.run(main())
  File "C:\Users\Patrick\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Patrick\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Patrick\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Dokumente\Patrick\RPi\Luefter\SIKU_Script_V2.py", line 126, in main
    await api.status()
  File "D:\Dokumente\Patrick\RPi\Luefter\SIKU_Script_V2.py", line 46, in status
    return await hexlist
           ^^^^^^^^^^^^^

**Comment by hmn** [comment]
I created a beta release of a version with v2 support

https://github.com/hmn/hacs-siku-integration/releases/tag/v2.0.0

it is still missing some stuff, so if you could enable debug logging and try it out and send me any output it is much appreciated

**Comment by victori3d** [comment]
Great job, very much appreciate your efforts.
I was able to configure my vent with your new release.
The following thinks are working so far:
Change State On and Off
Change Speed 0, 33, 66, 100%
Oscillate, Forward, Backward

Where i currently have trouble is activating Sleep or Party Mode.
Log for Party Mode and Sleep Mode:
2022-11-22 19:20:36.012 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
self.async_update_listeners()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
update_callback()
File "/config/custom_components/siku/fan.py", line 208, in _handle_coordinator_update
ordered_list_item_to_percentage(
File "/usr/src/homeassistant/homeassistant/util/percentage.py", line 25, in ordered_list_item_to_percentage
raise ValueError(f'The item "{item}"" is not in "{ordered_list}"')
ValueError: The item "1"" is not in "['01', '02', '03']"
2022-11-22 19:21:06.014 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
self.async_update_listeners()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
update_callback()
File "/config/custom_components/siku/fan.py", line 208, in _handle_coordinator_update
ordered_list_item_to_percentage(
File "/usr/src/homeassistant/homeassistant/util/percentage.py", line 25, in ordered_list_item_to_percentage
raise ValueError(f'The item "{item}"" is not in "{ordered_list}"')
ValueError: The item "1"" is not in "['01', '02', '03']"

**Comment by hmn** [comment]
I have fixed the speed status bug and added support for the modes
